apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: spring-k8s
          image: prakasitnan/spring-k8s:v1
          ports:
            - containerPort: 8080