apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-service
spec:
  type: NodePort
  selector:
    app: spring-k8s
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
